INSERT INTO categoria_produto (nome) VALUES
                                         ('Laticínios'),
                                         ('Padaria'),
                                         ('Congelados'),
                                         ('Fast Food'),
                                         ('Doces'),
                                         ('Bebidas'),
                                         ('Frios e Embutidos'),
                                         ('Alimentos Naturais'),
                                         ('Orgânicos'),
                                         ('Cereais e Grãos'),
                                         ('Molhos e Condimentos'),
                                         ('Carnes e Aves'),
                                         ('Peixes e Frutos do Mar'),
                                         ('Legumes e Verduras'),
                                         ('Frutas'),
                                         ('Snacks e Salgadinhos'),
                                         ('Comidas Prontas'),
                                         ('Pizzas'),
                                         ('Sobremesas'),
                                         ('Produtos Veganos'),
                                         ('Produtos Sem Glúten'),
                                         ('Produtos Sem Lactose'),
                                         ('Suplementos'),
                                         ('Produtos Gourmet'),
                                         ('Temperos e Especiarias');
