INSERT INTO categoria_estabelecimento (nome) VALUES
                                                 ('Mercado'),
                                                 ('Padaria'),
                                                 ('Restaurante'),
                                                 ('Lanchonete'),
                                                 ('Doceria'),
                                                 ('Açougue'),
                                                 ('Loja de Conveniência'),
                                                 ('Feira Livre'),
                                                 ('Pizzaria'),
                                                 ('Hamburgueria'),
                                                 ('Sorveteria'),
                                                 ('Sushi Bar / Japonês'),
                                                 ('Bar e Petiscaria'),
                                                 ('Loja Natural e Orgânica'),
                                                 ('Mercearia'),
                                                 ('Cafeteria'),
                                                 ('Restaurante Vegano'),
                                                 ('Food Truck'),
                                                 ('Empório'),
                                                 ('Loja de Produtos Gourmet'),
                                                 ('Loja de Bebidas'),
                                                 ('Hortifruti'),
                                                 ('Petiscaria'),
                                                 ('Padaria Artesanal'),
                                                 ('Churrascaria');
